name: Hello world
on: [push]
jobs: 
  "Hello-world":
     runs-on: ubuntu-latest
     steps:
       - name: "My first command"
         run: echo "Dominik"
       - name: "Checkout repository"
         uses: actions/checkout@v4
       - name: "show structure"
         run: tree ./
       - run: echo "it works"
       - run: mkdir /foo/moo/boo/zoo
       
